---
title: "Sandbox"
author: "Jacob Forbes"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align = "center")
```

```{r libraries}
library(dplyr)
library(ggplot2)
library(scales)
library(GGally)
library(SentimentAnalysis)
```

```{r}
# Load data
dat = read.csv("friends_and_the_office.csv")

# Convert variable types
dat$show = as.factor(dat$show)
dat$air_date = as.Date(dat$air_date, "%m/%d/%y")

# Show data structure
str(dat, vec.len = 1.2, nchar.max = 64)
```



```{r}
# Read in lines
lines = read.csv("The_Office_lines.csv")
```

```{r}
# Extract office
office = filter(dat, show == "The Office")
table(office$season)

# Check episodes
table(lines$season, lines$episode)
```


```{r}
# Check season 6
office6 = filter(office, season == 6)
lines6 = filter(lines, season == 6)


```

```{r}
lines = read.csv("The_Office_lines_v2.csv")


table(office$season)
table(lines$season, lines$episode)
```

```{r}
# Create Season/factor group
lines$season_ep = as.factor(paste(as.character(lines$season), as.character(lines$episode)))

# Create new aggregate data frame
lines_ag = aggregate(line_text~season_ep, data = lines, FUN=toString, na.rm=TRUE)



sentiment = analyzeSentiment(lines_ag$line_text, stemming = TRUE)
summary(sentiment)
```

```{r}
# Add sentiment score
office$sentiment = sentiment$SentimentGI

# Create plot
ggplot(data = office) +
  geom_point(aes(x = air_date, y = sentiment), size = 2) +
  labs(
    x = "Episode air date\n",
  ) +
  scale_y_continuous(name="Sentiment score", labels = comma) +
  theme(legend.position="top", 
        axis.text=element_text(size=16),
        axis.title=element_text(size=18,face="bold"),
        legend.title = element_text(size = 18, face = "bold"),
        legend.text = element_text(size = 16))
```

```{r}
# Create plot
ggplot(data = office) +
  geom_point(aes(x = sentiment, y = imdb_rating), size = 2) +
  labs(
    x = "Sentiment score",
  ) +
  scale_y_continuous(name="IMDB rating", labels = comma) +
  theme(legend.position="top", 
        axis.text=element_text(size=16),
        axis.title=element_text(size=18,face="bold"),
        legend.title = element_text(size = 18, face = "bold"),
        legend.text = element_text(size = 16))
```

```{r}
office$spos = sentiment$PositivityGI
office$sneg = sentiment$NegativityGI
mylm = lm(imdb_rating ~ spos + sneg, data = office)
summary(mylm)
```

```{r}
summary(sentiment)
office$sentimentHE = sentiment$SentimentHE
mylm = lm(imdb_rating ~ sentimentHE, data = office )
summary(mylm)
```

```{r}
ggplot(data = office) +
  geom_point(aes(x = sentimentHE, y = imdb_rating), size = 2) +
  labs(
    x = "Sentiment score",
  ) +
  scale_y_continuous(name="IMDB rating", labels = comma) +
  theme(legend.position="top", 
        axis.text=element_text(size=16),
        axis.title=element_text(size=18,face="bold"),
        legend.title = element_text(size = 18, face = "bold"),
        legend.text = element_text(size = 16))
```

```{r}
office = office[,1:9]
office = cbind(office,sentiment)

```

```{r}
office$wordGI = office$WordCount * office$SentimentGI
office$wordHE = office$WordCount * office$SentimentHE
office$wordLM = office$WordCount * office$SentimentLM
office$wordQDAP = office$WordCount * office$SentimentQDAP

ggpairs(data = office, columns = c(7,24:27), 
        aes(alpha = 0.5), size = 2) +
   # scale_y_continuous(labels = comma) +
   # scale_x_continuous(labels = comma) +
    theme( 
        axis.text=element_text(size=12),
        axis.title=element_text(size=12,face="bold"),
        legend.title = element_text(size = 12, face = "bold"),
        legend.text = element_text(size = 12))

```

```{r}
office$wordPosGI = office$WordCount * office$PositivityGI
office$wordPosHE = office$WordCount * office$PositivityHE
office$wordPosLM = office$WordCount * office$PositivityLM
office$wordPosQDAP = office$WordCount * office$PositivityQDAP

ggpairs(data = office, columns = c(7,28:31), 
        aes(alpha = 0.5), size = 2) +
   # scale_y_continuous(labels = comma) +
   # scale_x_continuous(labels = comma) +
    theme( 
        axis.text=element_text(size=12),
        axis.title=element_text(size=12,face="bold"),
        legend.title = element_text(size = 12, face = "bold"),
        legend.text = element_text(size = 12))
```

```{r}
office$wordVar = with(office, WordCount * (PositivityHE^2 + NegativityHE^2))
ggpairs(data = office, columns = c(32,7), 
        aes(alpha = 0.5), size = 2) +
   # scale_y_continuous(labels = comma) +
   # scale_x_continuous(labels = comma) +
    theme( 
        axis.text=element_text(size=12),
        axis.title=element_text(size=12,face="bold"),
        legend.title = element_text(size = 12, face = "bold"),
        legend.text = element_text(size = 12))
```


```{r}
office$wordNegHE = with(office, WordCount * NegativityHE)
ggpairs(data = office, columns = c(33,7), 
        aes(alpha = 0.5), size = 2) +
   # scale_y_continuous(labels = comma) +
   # scale_x_continuous(labels = comma) +
    theme( 
        axis.text=element_text(size=12),
        axis.title=element_text(size=12,face="bold"),
        legend.title = element_text(size = 12, face = "bold"),
        legend.text = element_text(size = 12))
```

```{r}
office$Michael_ep = grepl("Michael", office$description, fixed = TRUE)

mod3 = lm(imdb_rating ~ wordHE + Michael_ep,
   data = office)

summary(mod3)
plot(mod3)
```

